/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    people: Person;
    'external-videos': ExternalVideo;
    activities: Activity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'external-videos': ExternalVideosSelect<false> | ExternalVideosSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 管理后台账号、角色与基础资料。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 控制后台权限。超级管理员/管理员管理用户，内容编辑和素材管理员管理媒体，只读审阅用于查看资料。
   */
  role: 'superAdmin' | 'admin' | 'editor' | 'materialManager' | 'reviewer';
  /**
   * 用于后台列表和后续内容署名，比邮箱更便于识别。
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 公开图片、视频和档案素材库，供内容发布与活动资料复用。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 只有设为“允许公开读取”的素材才会通过公开 API 暴露。草稿活动素材建议保持仅后台可见。
   */
  visibility: 'private' | 'public';
  /**
   * 简短描述图片或视频封面内容，用于无障碍阅读和素材识别。
   */
  alt: string;
  caption?: string | null;
  /**
   * 记录摄影师、供稿人、机构、公众号或档案来源。
   */
  source?: string | null;
  /**
   * 为首页卡片、活动封面和后续视频封面裁切预留焦点。
   */
  previewFocus?: {
    x?: number | null;
    y?: number | null;
  };
  rights?: {
    copyright?: string | null;
    license?: ('unknown' | 'owned' | 'licensed' | 'publicDomain' | 'creativeCommons') | null;
    sourceUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 维护班级人物、活动嘉宾、主持人和同学资料，供活动纪要反复引用。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * 可选的英文唯一标识，后续公开人物页会用到。
   */
  slug?: string | null;
  roleCategory?: ('classmate' | 'guest' | 'faculty' | 'host' | 'staff' | 'other') | null;
  title?: string | null;
  /**
   * 填写所在企业、学校、协会或项目名称。
   */
  organization?: string | null;
  /**
   * 用于活动详情页的人物介绍，建议控制在 100 字以内。
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  profileLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 只有“已发布”且“允许公开展示”的人物会被前台公开读取。
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  isPublic?: boolean | null;
  sortOrder?: number | null;
  /**
   * 仅后台可见，用于记录沟通、授权或编辑备注。
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 登记外站视频的结构化信息和封面预览，不保存 iframe、script 或任意 HTML。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-videos".
 */
export interface ExternalVideo {
  id: number;
  title: string;
  provider: 'wechatChannels' | 'tencentVideo' | 'bilibili' | 'youku' | 'douyin' | 'youtube' | 'vimeo' | 'other';
  /**
   * 可选，填写平台侧视频 ID，便于后续生成预览或迁移。
   */
  providerId?: string | null;
  /**
   * 粘贴视频页面链接，不要粘贴 iframe、script 或任意 HTML。
   */
  sourceUrl: string;
  /**
   * 例如 03:20 或 1:12:30。
   */
  duration?: string | null;
  language?: string | null;
  captionStatus?: ('unknown' | 'none' | 'captioned' | 'transcribed') | null;
  /**
   * 优先上传已确认版权的封面图，前台用它显示视频预览。
   */
  coverImage?: (number | null) | Media;
  /**
   * 记录封面画面重点，例如“论坛合影”“嘉宾演讲特写”。
   */
  coverPreviewNote?: string | null;
  relatedActivities?: (number | Activity)[] | null;
  /**
   * 只有“已发布”的视频会被前台公开读取。
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  publishedAt?: string | null;
  /**
   * 记录视频授权、来源或公开展示限制。
   */
  rightsNote?: string | null;
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 像填写公众号推文一样，按固定模板整理活动标题、时间地点、正文、嘉宾、图集、视频和延伸阅读。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * 用于列表、详情页和后台检索，建议与公众号标题保持一致。
   */
  title: string;
  /**
   * 手动填写唯一英文地址，例如 alumni-salon-2026-04。
   */
  slug: string;
  /**
   * 用于列表卡片和详情页导语，建议 80-150 字。
   */
  summary: string;
  activityType?: ('classEvent' | 'salon' | 'companyVisit' | 'course' | 'sharing' | 'other') | null;
  /**
   * 活动主线或栏目名称，例如“产业参访”“同学分享会”。
   */
  theme?: string | null;
  /**
   * 用于活动详情页大标题下方；不填写时使用活动摘要。
   */
  subtitle?: string | null;
  /**
   * 用于相册页聚合，例如：戈壁挑战赛 / Ultra Gobi。
   */
  albumCategory?: string | null;
  /**
   * 例如 036。为空时前台使用默认编号。
   */
  archiveNumber?: string | null;
  /**
   * 例如 4 日 3 夜、121 公里。
   */
  durationLabel?: string | null;
  /**
   * 例如 Activity dossier、Ultra Gobi。
   */
  dossierLabel?: string | null;
  /**
   * 用于详情页 Date / Location / Participants / Editors 等信息。可少填，前台只展示有内容的项。
   */
  byline?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于详情页数据区，例如 121 公里、¥1.33M、35 人。为空时前台用照片/视频/链接等基础统计。
   */
  metrics?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于详情页时间线。为空时整个时间线区块不展示。
   */
  timeline?:
    | {
        time?: string | null;
        dateLabel?: string | null;
        title?: string | null;
        value?: string | null;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于还原 claudework 长文章正文。为空时使用上方富文本正文和摘要。
   */
  richBody?:
    | {
        blockType: 'paragraph' | 'heading' | 'quote' | 'figure' | 'orderedList';
        text?: string | null;
        level?: ('2' | '3') | null;
        attribution?: string | null;
        image?: (number | null) | Media;
        number?: string | null;
        tone?: number | null;
        credit?: string | null;
        caption?: string | null;
        items?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 手动指定详情页精选影像。为空时前台自动使用活动图集前 4 张。
   */
  photoStrip?: {
    title?: string | null;
    totalLabel?: string | null;
    href?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          caption: string;
          number?: string | null;
          tone?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * 用于详情页相关归档。为空时不展示相关区块。
   */
  relatedActivities?: (number | Activity)[] | null;
  eventDate: string;
  endDate?: string | null;
  /**
   * 用于按年份归档，例如 2026。
   */
  year: number;
  city?: string | null;
  venue?: string | null;
  locationNotes?: string | null;
  hosts?: (number | Person)[] | null;
  speakers?: (number | Person)[] | null;
  /**
   * 从人物库选择嘉宾、主持人或班级同学，避免重复手写姓名。
   */
  participants?: (number | Person)[] | null;
  /**
   * 填写活动纪要正文，可粘贴公众号式段落、标题和重点内容。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  agendaNotes?: string | null;
  highlights?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  outcomes?: string | null;
  followUps?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  quotes?:
    | {
        quote: string;
        person?: (number | null) | Person;
        id?: string | null;
      }[]
    | null;
  /**
   * 封面图用于首页推荐、活动卡片、详情页头图和分享预览。
   */
  cover?: {
    image?: (number | null) | Media;
    displayIntent?: ('archiveCard' | 'detailHero' | 'socialPreview' | 'editorialReference') | null;
    cropNote?: string | null;
    caption?: string | null;
    credit?: string | null;
    rightsNote?: string | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 选择已登记的外站视频素材，前台可展示视频封面和跳转链接。
   */
  videos?: (number | ExternalVideo)[] | null;
  /**
   * 只有“已发布”的活动纪要会被前台公开读取。
   */
  status: 'draft' | 'review' | 'published' | 'archived';
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * 供后台协作使用，不建议写入对外公开内容。
   */
  reviewNotes?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  relatedLinks?:
    | {
        title: string;
        url: string;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'external-videos';
        value: number | ExternalVideo;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  visibility?: T;
  alt?: T;
  caption?: T;
  source?: T;
  previewFocus?:
    | T
    | {
        x?: T;
        y?: T;
      };
  rights?:
    | T
    | {
        copyright?: T;
        license?: T;
        sourceUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  roleCategory?: T;
  title?: T;
  organization?: T;
  bio?: T;
  avatar?: T;
  profileLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  status?: T;
  isPublic?: T;
  sortOrder?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-videos_select".
 */
export interface ExternalVideosSelect<T extends boolean = true> {
  title?: T;
  provider?: T;
  providerId?: T;
  sourceUrl?: T;
  duration?: T;
  language?: T;
  captionStatus?: T;
  coverImage?: T;
  coverPreviewNote?: T;
  relatedActivities?: T;
  status?: T;
  publishedAt?: T;
  rightsNote?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  activityType?: T;
  theme?: T;
  subtitle?: T;
  albumCategory?: T;
  archiveNumber?: T;
  durationLabel?: T;
  dossierLabel?: T;
  byline?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        time?: T;
        dateLabel?: T;
        title?: T;
        value?: T;
        description?: T;
        id?: T;
      };
  richBody?:
    | T
    | {
        blockType?: T;
        text?: T;
        level?: T;
        attribution?: T;
        image?: T;
        number?: T;
        tone?: T;
        credit?: T;
        caption?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  photoStrip?:
    | T
    | {
        title?: T;
        totalLabel?: T;
        href?: T;
        items?:
          | T
          | {
              image?: T;
              caption?: T;
              number?: T;
              tone?: T;
              id?: T;
            };
      };
  relatedActivities?: T;
  eventDate?: T;
  endDate?: T;
  year?: T;
  city?: T;
  venue?: T;
  locationNotes?: T;
  hosts?: T;
  speakers?: T;
  participants?: T;
  content?: T;
  agendaNotes?: T;
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  outcomes?: T;
  followUps?:
    | T
    | {
        item?: T;
        id?: T;
      };
  quotes?:
    | T
    | {
        quote?: T;
        person?: T;
        id?: T;
      };
  cover?:
    | T
    | {
        image?: T;
        displayIntent?: T;
        cropNote?: T;
        caption?: T;
        credit?: T;
        rightsNote?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  videos?: T;
  status?: T;
  featured?: T;
  publishedAt?: T;
  reviewNotes?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  relatedLinks?:
    | T
    | {
        title?: T;
        url?: T;
        source?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 统一管理首页推荐、班级介绍、联系方式与默认 SEO。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  homeEyebrow?: string | null;
  homeTitle: string;
  homeSummary: string;
  homeStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  featuredActivities?: (number | Activity)[] | null;
  featuredPeople?: (number | Person)[] | null;
  className: string;
  classSubtitle?: string | null;
  classSummary: string;
  classHeroImage?: (number | null) | Media;
  classHighlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  classSections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  contactTitle: string;
  contactSummary: string;
  primaryEmail: string;
  locationLabel?: string | null;
  officeHours?: string | null;
  applyUrl?: string | null;
  /**
   * 说明填写邮箱后的处理方式，例如“将打开邮件客户端，不会在站点直接存储”。
   */
  newsletterNote?: string | null;
  contactChannels?:
    | {
        label: string;
        value: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  siteName: string;
  defaultTitle: string;
  defaultDescription: string;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  defaultOgImage?: (number | null) | Media;
  footerNote?: string | null;
  internalSeoNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  homeEyebrow?: T;
  homeTitle?: T;
  homeSummary?: T;
  homeStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featuredActivities?: T;
  featuredPeople?: T;
  className?: T;
  classSubtitle?: T;
  classSummary?: T;
  classHeroImage?: T;
  classHighlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  classSections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  contactTitle?: T;
  contactSummary?: T;
  primaryEmail?: T;
  locationLabel?: T;
  officeHours?: T;
  applyUrl?: T;
  newsletterNote?: T;
  contactChannels?:
    | T
    | {
        label?: T;
        value?: T;
        url?: T;
        id?: T;
      };
  siteName?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  defaultOgImage?: T;
  footerNote?: T;
  internalSeoNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}